io: Update answer for Q2
mariasfiraiala/SO-exam pull request #8
Opened 2023-02-03 16:42 UTC by Cynerdus

Signed-off-by: Cleopatra Popescu <cleopatra.popescu02@gmail.com>

2023-02-03 21:39 UTC, mariasfiraiala requested changes
Thanks @Cynerdus! Please apply the changes suggested below and keep only one commit for all of them. For the name, I suggest something along the lines: "{app-interact,io}: Add more details to questions".
Looks really clean, otherwise, we'll merge it quickly.

2023-02-03 21:39 UTC, mariasfiraiala commented on app-interact/app-interact-q&a.md
> +   De asemenea, sunt dependente de procesele asociate. Un pipe anonim este sters dupa terminarea procesului.
```suggestion
   De asemenea, sunt dependente de procesele asociate.
   Un pipe anonim este șters după terminarea procesului, spre deosebire de FIFO-uri care au un back-up în sistemul de fișiere virtual.
```

2023-02-03 21:39 UTC, mariasfiraiala commented on io/io-q&a.md
> +   Ca intrare pentru un descriptor de fișiere este reținut un pointer către un open file structure sau alta structura speciala, precum cea de socket, pipe sau terminal.
```suggestion
   Ca intrare pentru un descriptor de fișiere este reținut un pointer către un open channel structure.
```

2023-02-04 08:04 UTC, mariasfiraiala commented
@Cynerdus I see that you've integrated my suggestions, however now there are 4 commits to be merged (not elegant at all). Please squash them such that there is only one left with all the changes in it. If you're unsure of how to do this, let me know, I'll rebase your PR myself.

2023-02-04 08:15 UTC, Cynerdus commented
@mariasfiraiala Oh yes, thank you for letting me know. It appears I did not read your comment properly, my apologies. Later tonight when I have my unit available, I will squash the commits.

2023-02-04 08:24 UTC, mariasfiraiala commented
> @mariasfiraiala Oh yes, thank you for letting me know. It appears I did not read your comment properly, my apologies. Later tonight when I have my unit available, I will squash the commits.

Thank you :heart:

2023-02-04 18:47 UTC, Cynerdus commented
@mariasfiraiala Done.

2023-02-04 19:15 UTC, mariasfiraiala approved these changes
Looks alright. Thank you @Cynerdus!

2023-02-04 19:16 UTC, merged